# Generated by Django 5.0.7 on 2024-09-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0005_remove_customuser_last_active_customuser_is_online_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_online',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_seen',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_active_now',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
